In [3]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)

In [4]:
walk

[0,
 1,
 0,
 -1,
 -2,
 -3,
 -4,
 -3,
 -4,
 -3,
 -4,
 -5,
 -6,
 -7,
 -6,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -3,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -4,
 -5,
 -4,
 -3,
 -4,
 -3,
 -2,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 -1,
 0,
 -1,
 0,
 1,
 0,
 -1,
 -2,
 -3,
 -2,
 -1,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -6,
 -5,
 -6,
 -5,
 -4,
 -3,
 -4,
 -3,
 -2,
 -1,
 -2,
 -3,
 -4,
 -5,
 -4,
 -3,
 -4,
 -5,
 -6,
 -5,
 -6,
 -7,
 -8,
 -7,
 -6,
 -5,
 -4,
 -3,
 -2,
 -3,
 -2,
 -3,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 1,
 2,
 1,
 2,
 3,
 4,
 5,
 4,
 5,
 6,
 7,
 6,
 7,
 8,
 9,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 9,
 8,
 7,
 8,
 9,
 8,
 9,
 10,
 11,
 12,
 11,
 10,
 11,
 10,
 11,
 10,
 11,
 10,
 11,
 10,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 17,
 18,
 17,
 16,
 15,
 16,
 15,
 14,
 13,
 14,
 13,
 14,
 15,
 16,
 15,
 16,
 15,
 14,
 13,
 12,
 11,
 12,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 4,
 3,
 4,
 5,
 4,
 3,
 2,
 3,
 2,
 3,
 4,
 5,
 4

In [5]:
nsteps = 1000

In [6]:
import numpy as np

In [7]:
draws = np.random.randint(0, 2, size=nsteps)

In [8]:
steps = np.where(draws > 0, 1, -1)

In [9]:
walk = steps.cumsum()

In [10]:
walk

array([  1,   2,   3,   4,   5,   6,   5,   6,   5,   4,   3,   2,   1,
         0,  -1,   0,  -1,   0,   1,   2,   3,   2,   3,   4,   3,   2,
         1,   0,  -1,   0,   1,   2,   3,   2,   3,   2,   1,   2,   3,
         2,   3,   4,   5,   6,   7,   8,   7,   6,   5,   4,   5,   4,
         3,   4,   5,   6,   7,   6,   7,   6,   5,   6,   7,   6,   7,
         6,   7,   8,   7,   8,   7,   6,   7,   8,   7,   8,   9,   8,
         9,   8,   7,   6,   7,   8,   9,  10,  11,  10,  11,  10,   9,
        10,  11,  12,  11,  10,   9,  10,  11,  10,  11,  10,  11,  12,
        11,  10,  11,  12,  11,  10,   9,   8,   9,  10,   9,   8,   7,
         6,   7,   6,   7,   8,   7,   8,   7,   6,   5,   4,   5,   6,
         5,   4,   5,   4,   5,   6,   5,   4,   5,   4,   3,   2,   3,
         4,   3,   2,   1,   2,   3,   2,   1,   2,   1,   0,  -1,   0,
        -1,   0,   1,   2,   3,   4,   5,   4,   3,   2,   1,   2,   1,
         0,  -1,  -2,  -3,  -4,  -3,  -4,  -3,  -4,  -5,  -6,  -

In [11]:
walk.min()

-27

In [12]:
walk.max()

12

In [13]:
(np.abs(walk) >= 10).argmax()

85

In [14]:
nwalks = 5000

In [15]:
nsteps = 1000

In [16]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))

In [18]:
steps = np.where(draws > 0, 1, -1)

In [19]:
walks = steps.cumsum(1)

In [32]:
walks

array([[ -1,   0,  -1, ..., -38, -37, -36],
       [  1,   2,   1, ..., -22, -23, -22],
       [ -1,   0,   1, ...,  22,  21,  20],
       ..., 
       [  1,   2,   3, ...,  10,   9,   8],
       [  1,   2,   3, ...,  46,  47,  46],
       [  1,   0,  -1, ..., -30, -31, -32]], dtype=int32)

In [21]:
walks.max()

130

In [22]:
walks.min()

-112

In [28]:
hits30 = (np.abs(walks) >= 30).any(1)

In [29]:
hits30

array([ True, False,  True, ..., False,  True,  True], dtype=bool)

In [36]:
hits30.sum()

3419

In [38]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [39]:
crossing_times.mean()

498.06054401871893