In [1]:
import numpy as np

In [6]:
data = np.array([[0.9526, -0.246, -0.8856], [0.5639, 0.2379, 0.9104]])


In [7]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [8]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [9]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [18]:
arr2 = np.array(data2)

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [25]:
tmp = np.zeros(10)
tmp

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
tmp.dtype

dtype('float64')

In [27]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [28]:
np.empty((2,3,2))

array([[[ -1.28822975e-231,   2.68678435e+154],
        [  2.96439388e-323,   0.00000000e+000],
        [  0.00000000e+000,   6.82116729e-043]],

       [[  6.25646213e-091,   5.49604112e+170],
        [  3.61392414e+174,   1.52005180e-047],
        [  3.99910963e+252,   8.62757287e-309]]])

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [33]:
arr1.dtype

dtype('float64')

In [34]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [35]:
arr2.dtype

dtype('int32')

In [38]:
arr3 = arr2.astype(np.float64)

In [40]:
arr3.dtype

dtype('float64')

In [37]:
arr2

array([1, 2, 3], dtype=int32)

In [41]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [42]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [43]:
int_array = np.arange(10)

In [44]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [45]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [46]:
arr = np.arange(10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[5]

5

In [50]:
arr[5:8] = 12

In [51]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr_slice = arr[5:8]

In [53]:
arr_slice[1] = 12345

In [54]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [56]:
arr2d = np.array([[1,2,3], [4,5,6], [6,7,8]])

In [57]:
arr2d[2]

array([6, 7, 8])

In [58]:
arr2d[0][2]

3

In [59]:
arr2d[0,2]

3